micronaut:
  application:
    name: collected
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
datasources:
  default:
    # Use this for in-memory run
    # url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

    # Use this for devel
    url: jdbc:h2:tcp://localhost:9092/~/db/collected
    driverClassName: org.h2.Driver
    username: sa
    password: '1234'
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
