;
CREATE USER IF NOT EXISTS "SA" SALT '6809b8976868da08' HASH '97097576a633ddb6b8808186bc0b7fc96c34f22cec158ecf43df4675aa5d7c5a' ADMIN;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_FAD7B466_7F00_40A3_8154_0E499D5DC98C" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_01ADDE13_0FFA_4831_823F_93E1DC6F5891" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_5F417988_BB4F_4FCF_BB31_D3A710703994" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_7A5C5893_B851_446F_B2ED_B0141259DD30" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_623F5807_7654_426F_8152_691741FDAD48" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_CD1A8A82_6F68_45AA_98D4_714F373DCA06" START WITH 1 BELONGS_TO_TABLE;
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "USER_ID" INT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_CD1A8A82_6F68_45AA_98D4_714F373DCA06" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_CD1A8A82_6F68_45AA_98D4_714F373DCA06",
    "USERNAME" VARCHAR(50) NOT NULL,
    "PASSWORD" VARCHAR(64) NOT NULL,
    "EMAIL" VARCHAR(100) NOT NULL
);
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."USERS_PK" PRIMARY KEY("USER_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USERS;
CREATE UNIQUE INDEX "PUBLIC"."USERS_USERNAME_UINDEX" ON "PUBLIC"."USERS"("USERNAME");
CREATE UNIQUE INDEX "PUBLIC"."USERS_USER_ID_UINDEX" ON "PUBLIC"."USERS"("USER_ID");
CREATE CACHED TABLE "PUBLIC"."ITEM_LISTS"(
    "ITEM_LIST_ID" INT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_01ADDE13_0FFA_4831_823F_93E1DC6F5891" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_01ADDE13_0FFA_4831_823F_93E1DC6F5891",
    "LIST_TYPE" TEXT NOT NULL,
    "SORT_PREFERENCE" TEXT NOT NULL,
    "OWNER_ID" INT NOT NULL
);
ALTER TABLE "PUBLIC"."ITEM_LISTS" ADD CONSTRAINT "PUBLIC"."ITEM_LISTS_PK" PRIMARY KEY("ITEM_LIST_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ITEM_LISTS;
CREATE UNIQUE INDEX "PUBLIC"."ITEM_LISTS_ITEM_LIST_ID_UINDEX" ON "PUBLIC"."ITEM_LISTS"("ITEM_LIST_ID");
CREATE CACHED TABLE "PUBLIC"."WISHLISTS"(
    "WISHLIST_ID" INT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_5F417988_BB4F_4FCF_BB31_D3A710703994" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_5F417988_BB4F_4FCF_BB31_D3A710703994",
    "OWNER_ID" INT NOT NULL
);
ALTER TABLE "PUBLIC"."WISHLISTS" ADD CONSTRAINT "PUBLIC"."WISHLISTS_PK" PRIMARY KEY("WISHLIST_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.WISHLISTS;
CREATE UNIQUE INDEX "PUBLIC"."WISHLISTS_WISHLIST_ID_UINDEX" ON "PUBLIC"."WISHLISTS"("WISHLIST_ID");
CREATE CACHED TABLE "PUBLIC"."ITEM_DESCRIPTIONS"(
    "DESCRIPTION_ID" INT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_7A5C5893_B851_446F_B2ED_B0141259DD30" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_7A5C5893_B851_446F_B2ED_B0141259DD30",
    "NAME" TEXT NOT NULL,
    "ITEM_TYPE" TEXT NOT NULL,
    "DESCRIPTION" TEXT NOT NULL,
    "RELEASE_DATE" DATETIME NOT NULL
);
ALTER TABLE "PUBLIC"."ITEM_DESCRIPTIONS" ADD CONSTRAINT "PUBLIC"."ITEM_DESCRIPTIONS_PK" PRIMARY KEY("DESCRIPTION_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ITEM_DESCRIPTIONS;
CREATE UNIQUE INDEX "PUBLIC"."ITEM_DESCRIPTIONS_DESCRIPTION_ID_UINDEX" ON "PUBLIC"."ITEM_DESCRIPTIONS"("DESCRIPTION_ID");
CREATE CACHED TABLE "PUBLIC"."ITEM_LIST_ITEMS"(
    "LIST_ITEM_ID" INT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_FAD7B466_7F00_40A3_8154_0E499D5DC98C" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_FAD7B466_7F00_40A3_8154_0E499D5DC98C",
    "RATING" INT NOT NULL,
    "ITEM_DESCRIPTION_ID" INT NOT NULL,
    "ITEM_LIST_ID" INT NOT NULL
);
ALTER TABLE "PUBLIC"."ITEM_LIST_ITEMS" ADD CONSTRAINT "PUBLIC"."ITEM_LIST_ITEMS_PK" PRIMARY KEY("LIST_ITEM_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ITEM_LIST_ITEMS;
CREATE UNIQUE INDEX "PUBLIC"."ITEM_LIST_ITEMS_LIST_ITEM_ID_UINDEX" ON "PUBLIC"."ITEM_LIST_ITEMS"("LIST_ITEM_ID");
CREATE CACHED TABLE "PUBLIC"."WISHLIST_ITEMS"(
    "WISHLIST_ITEM_ID" INT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_623F5807_7654_426F_8152_691741FDAD48" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_623F5807_7654_426F_8152_691741FDAD48",
    "ITEM_DESCRIPTION_ID" INT NOT NULL,
    "WISHLIST_ID" INT NOT NULL
);
ALTER TABLE "PUBLIC"."WISHLIST_ITEMS" ADD CONSTRAINT "PUBLIC"."WISHLIST_ITEMS_PK" PRIMARY KEY("WISHLIST_ITEM_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.WISHLIST_ITEMS;
CREATE UNIQUE INDEX "PUBLIC"."WISHLIST_ITEMS_WISHLIST_ITEM_ID_UINDEX" ON "PUBLIC"."WISHLIST_ITEMS"("WISHLIST_ITEM_ID");
ALTER TABLE "PUBLIC"."ITEM_LIST_ITEMS" ADD CONSTRAINT "PUBLIC"."ITEM_LIST_ITEMS_ITEM_LISTS_ITEM_LIST_ID_FK" FOREIGN KEY("ITEM_LIST_ID") REFERENCES "PUBLIC"."ITEM_LISTS"("ITEM_LIST_ID") NOCHECK;
ALTER TABLE "PUBLIC"."ITEM_LISTS" ADD CONSTRAINT "PUBLIC"."ITEM_LISTS_USERS_USER_ID_FK" FOREIGN KEY("OWNER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") ON DELETE CASCADE NOCHECK;
ALTER TABLE "PUBLIC"."WISHLIST_ITEMS" ADD CONSTRAINT "PUBLIC"."WISHLIST_ITEMS_ITEM_DESCRIPTIONS_DESCRIPTION_ID_FK" FOREIGN KEY("ITEM_DESCRIPTION_ID") REFERENCES "PUBLIC"."ITEM_DESCRIPTIONS"("DESCRIPTION_ID") ON DELETE CASCADE NOCHECK;
ALTER TABLE "PUBLIC"."ITEM_LIST_ITEMS" ADD CONSTRAINT "PUBLIC"."ITEM_LIST_ITEMS_ITEM_DESCRIPTIONS_DESCRIPTION_ID_FK" FOREIGN KEY("ITEM_DESCRIPTION_ID") REFERENCES "PUBLIC"."ITEM_DESCRIPTIONS"("DESCRIPTION_ID") ON DELETE CASCADE NOCHECK;
ALTER TABLE "PUBLIC"."WISHLIST_ITEMS" ADD CONSTRAINT "PUBLIC"."WISHLIST_ITEMS_WISHLISTS_WISHLIST_ID_FK" FOREIGN KEY("WISHLIST_ID") REFERENCES "PUBLIC"."WISHLISTS"("WISHLIST_ID") ON DELETE CASCADE NOCHECK;
ALTER TABLE "PUBLIC"."WISHLISTS" ADD CONSTRAINT "PUBLIC"."WISHLISTS_USERS_USER_ID_FK" FOREIGN KEY("OWNER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;
